# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-09 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='address',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='city',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='country',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='state',
        ),
    ]
