# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-09 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20161209_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='dni',
        ),
        migrations.AddField(
            model_name='partner',
            name='city',
            field=models.CharField(default='Madrid', max_length=50),
            preserve_default=False,
        ),
    ]
